"""init

Revision ID: 0c21ed11208f
Revises:
Create Date: 2020-08-19 13:27:29.116539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c21ed11208f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('left_appts',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seven', sa.Text(), nullable=True),
    sa.Column('eight', sa.Text(), nullable=True),
    sa.Column('nine', sa.Text(), nullable=True),
    sa.Column('ten', sa.Text(), nullable=True),
    sa.Column('eleven', sa.Text(), nullable=True),
    sa.Column('twelve', sa.Text(), nullable=True),
    sa.Column('thirteen', sa.Text(), nullable=True),
    sa.Column('fourteen', sa.Text(), nullable=True),
    sa.Column('fifteen', sa.Text(), nullable=True),
    sa.Column('sixteen', sa.Text(), nullable=True),
    sa.Column('seveteen', sa.Text(), nullable=True),
    sa.Column('eighteen', sa.Text(), nullable=True),
    sa.Column('nineteen', sa.Text(), nullable=True),
    sa.Column('twenty', sa.Text(), nullable=True),
    sa.Column('twentyone', sa.Text(), nullable=True),
    sa.Column('twentytwo', sa.Text(), nullable=True),
    sa.Column('twentythree', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_left_appts'))
    )
    op.create_table('right_appts',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seven', sa.Text(), nullable=True),
    sa.Column('eight', sa.Text(), nullable=True),
    sa.Column('nine', sa.Text(), nullable=True),
    sa.Column('ten', sa.Text(), nullable=True),
    sa.Column('eleven', sa.Text(), nullable=True),
    sa.Column('twelve', sa.Text(), nullable=True),
    sa.Column('thirteen', sa.Text(), nullable=True),
    sa.Column('fourteen', sa.Text(), nullable=True),
    sa.Column('fifteen', sa.Text(), nullable=True),
    sa.Column('sixteen', sa.Text(), nullable=True),
    sa.Column('seveteen', sa.Text(), nullable=True),
    sa.Column('eighteen', sa.Text(), nullable=True),
    sa.Column('nineteen', sa.Text(), nullable=True),
    sa.Column('twenty', sa.Text(), nullable=True),
    sa.Column('twentyone', sa.Text(), nullable=True),
    sa.Column('twentytwo', sa.Text(), nullable=True),
    sa.Column('twentythree', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_right_appts'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('right_appts')
    op.drop_table('left_appts')
    # ### end Alembic commands ###
